declare type u8=number //uint8
declare type f32=number
declare type f64=number
declare type u32=number
declare type i32=number
declare type u16=number
declare type NormalizedF32=number
declare type bool=boolean
declare type FiniteF32=number
declare type Option<T>=T|undefined
declare type usize=number
declare type FDot16 = i32;
declare type AlphaU8 = u8;
declare type NormalizedF32Exclusive=number // 0<value<1