
var PathKitInit = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
function(moduleArg = {}) {
  var moduleRtn;

var n=moduleArg,aa,ba,ca=new Promise((b,a)=>{aa=b;ba=a}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;
(function(b){var a={};b.loadCmdsTypedArray=function(f){for(var k=0,m=0;m<f.length;m++)k+=f[m].length;if(a[k])var l=a[k];else l=new Float32Array(k),a[k]=l;var p=0;for(m=0;m<f.length;m++)for(var r=0;r<f[m].length;r++){var w=f[m][r];"string"===typeof w&&(w=b.SkBits2FloatUnsigned(parseInt(w)));l[p]=w;p++}f=b._malloc(l.length*l.BYTES_PER_ELEMENT);b.HEAPF32.set(l,f/l.BYTES_PER_ELEMENT);return[f,k]};b.FromCmds=function(f){f=b.loadCmdsTypedArray(f);var k=b._FromCmds(f[0],f[1]);b._free(f[0]);return k};var c,
d,e,g,h;b.cubicYFromX=function(f,k,m,l,p){c&&d===f&&e===k&&g===m&&h===l||(c&&c.delete(),c=new b._SkCubicMap([f,k],[m,l]),d=f,e=k,g=m,h=l);return c.computeYFromX(p)};b.cubicPtFromT=function(f,k,m,l,p){c&&d===f&&e===k&&g===m&&h===l||(c&&c.delete(),c=new b._SkCubicMap([f,k],[m,l]),d=f,e=k,g=m,h=l);return c.computePtFromT(p)}})(n);
(function(b){b.onRuntimeInitialized=function(){b.SkPath.prototype.addPath=function(){var a=arguments[0];if(1===arguments.length)this._addPath(a,1,0,0,0,1,0,0,0,1);else if(2===arguments.length){var c=arguments[1];this._addPath(a,c.a,c.c,c.e,c.b,c.d,c.f,0,0,1)}else if(7===arguments.length)c=arguments,this._addPath(a,c[1],c[3],c[5],c[2],c[4],c[6],0,0,1);else if(10===arguments.length)c=arguments,this._addPath(a,c[1],c[2],c[3],c[4],c[5],c[6],c[7],c[8],c[9]);else return console.Ja("addPath expected to take 1, 2, 7, or 10 args. Got "+
arguments.length),null;return this};b.SkPath.prototype.arc=function(a,c,d,e,g,h){this._arc(a,c,d,e,g,!!h);return this};b.SkPath.prototype.arcTo=function(a,c,d,e,g){this._arcTo(a,c,d,e,g);return this};b.SkPath.prototype.bezierCurveTo=function(a,c,d,e,g,h){this._cubicTo(a,c,d,e,g,h);return this};b.SkPath.prototype.close=function(){this._close();return this};b.SkPath.prototype.closePath=function(){this._close();return this};b.SkPath.prototype.conicTo=function(a,c,d,e,g){this._conicTo(a,c,d,e,g);return this};
b.SkPath.prototype.cubicTo=function(a,c,d,e,g,h){this._cubicTo(a,c,d,e,g,h);return this};b.SkPath.prototype.dash=function(a,c,d){return this._dash(a,c,d)?this:null};b.SkPath.prototype.ellipse=function(a,c,d,e,g,h,f,k){this._ellipse(a,c,d,e,g,h,f,!!k);return this};b.SkPath.prototype.lineTo=function(a,c){this._lineTo(a,c);return this};b.SkPath.prototype.moveTo=function(a,c){this._moveTo(a,c);return this};b.SkPath.prototype.op=function(a,c){return this._op(a,c)?this:null};b.SkPath.prototype.quadraticCurveTo=
function(a,c,d,e){this._quadTo(a,c,d,e);return this};b.SkPath.prototype.quadTo=function(a,c,d,e){this._quadTo(a,c,d,e);return this};b.SkPath.prototype.rect=function(a,c,d,e){this._rect(a,c,d,e);return this};b.SkPath.prototype.simplify=function(){return this._simplify()?this:null};b.SkPath.prototype.stroke=function(a){a=a||{};a.width=a.width||1;a.miter_limit=a.miter_limit||4;a.cap=a.cap||b.StrokeCap.BUTT;a.join=a.join||b.StrokeJoin.MITER;a.res_scale=a.res_scale||1;return this._stroke(a)?this:null};
b.SkPath.prototype.transform=function(){if(1===arguments.length)this._transform(arguments[0]);else if(9===arguments.length){var a=arguments;this._transform(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8])}else return console.Ja("transform expected to take 1 or 9 arguments. Got "+arguments.length),null;return this};b.SkPath.prototype.trim=function(a,c,d){return this._trim(a,c,!!d)?this:null};b.SkPath.prototype.contains=function(a,c){return this._contains(a,c)}}})(n);
var ha=Object.assign({},n),q="",ia,v;
if(fa){var fs=require("fs"),ja=require("path");q=__dirname+"/";v=b=>{b=x(b)?new URL(b):ja.normalize(b);return fs.readFileSync(b)};ia=b=>{b=x(b)?new URL(b):ja.normalize(b);return new Promise((a,c)=>{fs.readFile(b,void 0,(d,e)=>{d?c(d):a(e.buffer)})})};process.argv.slice(2)}else if(da||ea)ea?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptName&&(q=_scriptName),q.startsWith("blob:")?q="":q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+
1),ea&&(v=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)}),ia=b=>x(b)?new Promise((a,c)=>{var d=new XMLHttpRequest;d.open("GET",b,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?a(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(b,{credentials:"same-origin"}).then(a=>a.ok?a.arrayBuffer():Promise.reject(Error(a.status+" : "+a.url)));var ka=console.log.bind(console),y=console.error.bind(console);
Object.assign(n,ha);ha=null;var A,la=!1,ma,B,D,E,F,G,na,oa;function pa(){var b=A.buffer;ma=new Int8Array(b);D=new Int16Array(b);B=new Uint8Array(b);E=new Uint16Array(b);F=new Int32Array(b);G=new Uint32Array(b);na=new Float32Array(b);oa=new Float64Array(b)}var qa=[],ra=[],sa=[],H=0,ta=null,I=null;function ua(b){b="Aborted("+b+")";y(b);la=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ba(b);throw b;}
var va=b=>b.startsWith("data:application/octet-stream;base64,"),x=b=>b.startsWith("file://"),wa;function xa(b){return ia(b).then(a=>new Uint8Array(a),()=>{if(v)var a=v(b);else throw"both async and sync fetching of the wasm failed";return a})}function ya(b,a,c){return xa(b).then(d=>WebAssembly.instantiate(d,a)).then(c,d=>{y(`failed to asynchronously prepare wasm: ${d}`);ua(d)})}
function za(b,a){var c=wa;return"function"!=typeof WebAssembly.instantiateStreaming||va(c)||x(c)||fa||"function"!=typeof fetch?ya(c,b,a):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,b).then(a,function(e){y(`wasm streaming compile failed: ${e}`);y("falling back to ArrayBuffer instantiation");return ya(c,b,a)}))}var Aa={},Ba=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function J(b){return this.fromWireType(G[b>>2])}
var L={},M={},Ca={},N,P=(b,a,c)=>{function d(f){f=c(f);if(f.length!==b.length)throw new N("Mismatched type converter count");for(var k=0;k<b.length;++k)O(b[k],f[k])}b.forEach(f=>Ca[f]=a);var e=Array(a.length),g=[],h=0;a.forEach((f,k)=>{M.hasOwnProperty(f)?e[k]=M[f]:(g.push(f),L.hasOwnProperty(f)||(L[f]=[]),L[f].push(()=>{e[k]=M[f];++h;h===g.length&&d(e)}))});0===g.length&&d(e)},Da={},Ea,Q=b=>{for(var a="";B[b];)a+=Ea[B[b++]];return a},R;
function Ga(b,a,c={}){var d=a.name;if(!b)throw new R(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(b)){if(c.Oa)return;throw new R(`Cannot register type '${d}' twice`);}M[b]=a;delete Ca[b];L.hasOwnProperty(b)&&(a=L[b],delete L[b],a.forEach(e=>e()))}function O(b,a,c={}){return Ga(b,a,c)}
var Ha=b=>{throw new R(b.da.ga.ea.name+" instance already deleted");},Ia=!1,Ja=()=>{},Ka=(b,a,c)=>{if(a===c)return b;if(void 0===c.ja)return null;b=Ka(b,a,c.ja);return null===b?null:c.Ka(b)},La={},Ma={},Na=(b,a)=>{if(void 0===a)throw new R("ptr should not be undefined");for(;b.ja;)a=b.ua(a),b=b.ja;return Ma[a]},Oa=(b,a)=>{if(!a.ga||!a.fa)throw new N("makeClassHandle requires ptr and ptrType");if(!!a.na!==!!a.ia)throw new N("Both smartPtrType and smartPtr must be specified");a.count={value:1};return S(Object.create(b,
{da:{value:a,writable:!0}}))},S=b=>{if("undefined"===typeof FinalizationRegistry)return S=a=>a,b;Ia=new FinalizationRegistry(a=>{a=a.da;--a.count.value;0===a.count.value&&(a.ia?a.na.ma(a.ia):a.ga.ea.ma(a.fa))});S=a=>{var c=a.da;c.ia&&Ia.register(a,{da:c},a);return a};Ja=a=>{Ia.unregister(a)};return S(b)},Pa=[];function Qa(){}
var T=(b,a)=>Object.defineProperty(a,"name",{value:b}),Ra=(b,a,c)=>{if(void 0===b[a].ha){var d=b[a];b[a]=function(...e){if(!b[a].ha.hasOwnProperty(e.length))throw new R(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].ha})!`);return b[a].ha[e.length].apply(this,e)};b[a].ha=[];b[a].ha[d.qa]=d}},Sa=(b,a,c)=>{if(n.hasOwnProperty(b)){if(void 0===c||void 0!==n[b].ha&&void 0!==n[b].ha[c])throw new R(`Cannot register public name '${b}' twice`);Ra(n,b,b);
if(n[b].ha.hasOwnProperty(c))throw new R(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[b].ha[c]=a}else n[b]=a,n[b].qa=c},Ta=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Ua(b,a,c,d,e,g,h,f){this.name=b;this.constructor=a;this.pa=c;this.ma=d;this.ja=e;this.Ma=g;this.ua=h;this.Ka=f;this.Qa=[]}
var Va=(b,a,c)=>{for(;a!==c;){if(!a.ua)throw new R(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.ua(b);a=a.ja}return b};function Wa(b,a){if(null===a){if(this.Aa)throw new R(`null is not a valid ${this.name}`);return 0}if(!a.da)throw new R(`Cannot pass "${Xa(a)}" as a ${this.name}`);if(!a.da.fa)throw new R(`Cannot pass deleted object as a pointer of type ${this.name}`);return Va(a.da.fa,a.da.ga.ea,this.ea)}
function Ya(b,a){if(null===a){if(this.Aa)throw new R(`null is not a valid ${this.name}`);if(this.wa){var c=this.ta();null!==b&&b.push(this.ma,c);return c}return 0}if(!a||!a.da)throw new R(`Cannot pass "${Xa(a)}" as a ${this.name}`);if(!a.da.fa)throw new R(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.va&&a.da.ga.va)throw new R(`Cannot convert argument of type ${a.da.na?a.da.na.name:a.da.ga.name} to parameter type ${this.name}`);c=Va(a.da.fa,a.da.ga.ea,this.ea);if(this.wa){if(void 0===
a.da.ia)throw new R("Passing raw pointer to smart pointer is illegal");switch(this.Sa){case 0:if(a.da.na===this)c=a.da.ia;else throw new R(`Cannot convert argument of type ${a.da.na?a.da.na.name:a.da.ga.name} to parameter type ${this.name}`);break;case 1:c=a.da.ia;break;case 2:if(a.da.na===this)c=a.da.ia;else{var d=a.clone();c=this.Ra(c,U(()=>d["delete"]()));null!==b&&b.push(this.ma,c)}break;default:throw new R("Unsupporting sharing policy");}}return c}
function Za(b,a){if(null===a){if(this.Aa)throw new R(`null is not a valid ${this.name}`);return 0}if(!a.da)throw new R(`Cannot pass "${Xa(a)}" as a ${this.name}`);if(!a.da.fa)throw new R(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.da.ga.va)throw new R(`Cannot convert argument of type ${a.da.ga.name} to parameter type ${this.name}`);return Va(a.da.fa,a.da.ga.ea,this.ea)}
function $a(b,a,c,d,e,g,h,f,k,m,l){this.name=b;this.ea=a;this.Aa=c;this.va=d;this.wa=e;this.Pa=g;this.Sa=h;this.Ha=f;this.ta=k;this.Ra=m;this.ma=l;e||void 0!==a.ja?this.toWireType=Ya:(this.toWireType=d?Wa:Za,this.la=null)}
var ab=(b,a,c)=>{if(!n.hasOwnProperty(b))throw new N("Replacing nonexistent public symbol");void 0!==n[b].ha&&void 0!==c?n[b].ha[c]=a:(n[b]=a,n[b].qa=c)},bb,cb=(b,a,c=[])=>{b.includes("j")?(b=b.replace(/p/g,"i"),a=(0,n["dynCall_"+b])(a,...c)):a=bb.get(a)(...c);return a},db=(b,a)=>(...c)=>cb(b,a,c),V=(b,a)=>{b=Q(b);var c=b.includes("j")?db(b,a):bb.get(a);if("function"!=typeof c)throw new R(`unknown function pointer with signature ${b}: ${a}`);return c},eb,gb=b=>{b=fb(b);var a=Q(b);X(b);return a},hb=
(b,a)=>{function c(g){e[g]||M[g]||(Ca[g]?Ca[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};a.forEach(c);throw new eb(`${b}: `+d.map(gb).join([", "]));},ib=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c};function kb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].la)return!0;return!1}
function lb(b,a,c,d,e){var g=a.length;if(2>g)throw new R("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==a[1]&&null!==c,f=kb(a),k="void"!==a[0].name,m=g-2,l=Array(m),p=[],r=[];return T(b,function(...w){r.length=0;p.length=h?2:1;p[0]=e;if(h){var t=a[1].toWireType(r,this);p[1]=t}for(var u=0;u<m;++u)l[u]=a[u+2].toWireType(r,w[u]),p.push(l[u]);w=d(...p);if(f)Ba(r);else for(u=h?1:2;u<a.length;u++){var C=1===u?t:l[u-2];null!==a[u].la&&a[u].la(C)}t=k?a[0].fromWireType(w):
void 0;return t})}
var mb=b=>{b=b.trim();const a=b.indexOf("(");return-1!==a?b.substr(0,a):b},nb=[],Y=[],ob=b=>{9<b&&0===--Y[b+1]&&(Y[b]=void 0,nb.push(b))},pb=b=>{if(!b)throw new R("Cannot use deleted val. handle = "+b);return Y[b]},U=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=nb.pop()||Y.length;Y[a]=b;Y[a+1]=1;return a}},qb={name:"emscripten::val",fromWireType:b=>{var a=pb(b);ob(b);return a},toWireType:(b,a)=>U(a),ka:8,readValueFromPointer:J,la:null},rb=
(b,a,c)=>{switch(a){case 1:return c?function(d){return this.fromWireType(ma[d])}:function(d){return this.fromWireType(B[d])};case 2:return c?function(d){return this.fromWireType(D[d>>1])}:function(d){return this.fromWireType(E[d>>1])};case 4:return c?function(d){return this.fromWireType(F[d>>2])}:function(d){return this.fromWireType(G[d>>2])};default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},sb=(b,a)=>{var c=M[b];if(void 0===c)throw b=`${a} has unknown type ${gb(b)}`,new R(b);return c},
Xa=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b},tb=(b,a)=>{switch(a){case 4:return function(c){return this.fromWireType(na[c>>2])};case 8:return function(c){return this.fromWireType(oa[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},ub=(b,a,c)=>{switch(a){case 1:return c?d=>ma[d]:d=>B[d];case 2:return c?d=>D[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];default:throw new TypeError(`invalid integer width (${a}): ${b}`);
}},vb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,wb=(b,a=0,c=NaN)=>{var d=a+c;for(c=a;b[c]&&!(c>=d);)++c;if(16<c-a&&b.buffer&&vb)return vb.decode(b.subarray(a,c));for(d="";a<c;){var e=b[a++];if(e&128){var g=b[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=b[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|b[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
xb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,yb=(b,a)=>{var c=b>>1;for(var d=c+a/2;!(c>=d)&&E[c];)++c;c<<=1;if(32<c-b&&xb)return xb.decode(B.subarray(b,c));c="";for(d=0;!(d>=a/2);++d){var e=D[b+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},zb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)D[a>>1]=b.charCodeAt(e),a+=2;D[a>>1]=0;return a-d},Ab=b=>2*b.length,Bb=(b,a)=>{for(var c=0,d="";!(c>=a/4);){var e=F[b+4*
c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Cb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var g=b.charCodeAt(e);if(55296<=g&&57343>=g){var h=b.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}F[a>>2]=g;a+=4;if(a+4>c)break}F[a>>2]=0;return a-d},Db=b=>{for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);55296<=d&&57343>=d&&++c;a+=4}return a},Eb=[],Fb={},Gb=b=>{var a=Fb[b];return void 0===
a?Q(b):a},Hb=()=>{function b(a){a.$$$embind_global$$$=a;var c="object"==typeof $$$embind_global$$$&&a.$$$embind_global$$$==a;c||delete a.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&b(global)?$$$embind_global$$$=global:"object"==typeof self&&b(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
},Ib=b=>{var a=Eb.length;Eb.push(b);return a},Jb=(b,a)=>{for(var c=Array(b),d=0;d<b;++d)c[d]=sb(G[a+4*d>>2],"parameter "+d);return c},Kb=Reflect.construct,Lb=[null,[],[]];N=n.InternalError=class extends Error{constructor(b){super(b);this.name="InternalError"}};for(var Mb=Array(256),Nb=0;256>Nb;++Nb)Mb[Nb]=String.fromCharCode(Nb);Ea=Mb;R=n.BindingError=class extends Error{constructor(b){super(b);this.name="BindingError"}};
Object.assign(Qa.prototype,{isAliasOf:function(b){if(!(this instanceof Qa&&b instanceof Qa))return!1;var a=this.da.ga.ea,c=this.da.fa;b.da=b.da;var d=b.da.ga.ea;for(b=b.da.fa;a.ja;)c=a.ua(c),a=a.ja;for(;d.ja;)b=d.ua(b),d=d.ja;return a===d&&c===b},clone:function(){this.da.fa||Ha(this);if(this.da.sa)return this.da.count.value+=1,this;var b=S,a=Object,c=a.create,d=Object.getPrototypeOf(this),e=this.da;b=b(c.call(a,d,{da:{value:{count:e.count,ra:e.ra,sa:e.sa,fa:e.fa,ga:e.ga,ia:e.ia,na:e.na}}}));b.da.count.value+=
1;b.da.ra=!1;return b},["delete"](){this.da.fa||Ha(this);if(this.da.ra&&!this.da.sa)throw new R("Object already scheduled for deletion");Ja(this);var b=this.da;--b.count.value;0===b.count.value&&(b.ia?b.na.ma(b.ia):b.ga.ea.ma(b.fa));this.da.sa||(this.da.ia=void 0,this.da.fa=void 0)},isDeleted:function(){return!this.da.fa},deleteLater:function(){this.da.fa||Ha(this);if(this.da.ra&&!this.da.sa)throw new R("Object already scheduled for deletion");Pa.push(this);this.da.ra=!0;return this}});
Object.assign($a.prototype,{Na(b){this.Ha&&(b=this.Ha(b));return b},Fa(b){this.ma?.(b)},ka:8,readValueFromPointer:J,fromWireType:function(b){function a(){return this.wa?Oa(this.ea.pa,{ga:this.Pa,fa:c,na:this,ia:b}):Oa(this.ea.pa,{ga:this,fa:b})}var c=this.Na(b);if(!c)return this.Fa(b),null;var d=Na(this.ea,c);if(void 0!==d){if(0===d.da.count.value)return d.da.fa=c,d.da.ia=b,d.clone();d=d.clone();this.Fa(b);return d}d=this.ea.Ma(c);d=La[d];if(!d)return a.call(this);d=this.va?d.Ia:d.pointerType;var e=
Ka(c,this.ea,d.ea);return null===e?a.call(this):this.wa?Oa(d.ea.pa,{ga:d,fa:e,na:this,ia:b}):Oa(d.ea.pa,{ga:d,fa:e})}});eb=n.UnboundTypeError=((b,a)=>{var c=T(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Y.push(0,1,void 0,1,null,1,!0,1,!1,1);n.count_emval_handles=()=>Y.length/2-5-nb.length;
var Pb={A:()=>{ua("")},u:b=>{var a=Aa[b];delete Aa[b];var c=a.elements,d=c.length,e=c.map(f=>f.za).concat(c.map(f=>f.Ca)),g=a.ta,h=a.ma;P([b],e,f=>{c.forEach((k,m)=>{var l=f[m],p=k.xa,r=k.ya,w=f[m+d],t=k.Ba,u=k.Da;k.read=C=>l.fromWireType(p(r,C));k.write=(C,K)=>{var z=[];t(u,C,w.toWireType(z,K));Ba(z)}});return[{name:a.name,fromWireType:k=>{for(var m=Array(d),l=0;l<d;++l)m[l]=c[l].read(k);h(k);return m},toWireType:(k,m)=>{if(d!==m.length)throw new TypeError(`Incorrect number of tuple elements for ${a.name}: expected=${d}, actual=${m.length}`);
for(var l=g(),p=0;p<d;++p)c[p].write(l,m[p]);null!==k&&k.push(h,l);return l},ka:8,readValueFromPointer:J,la:h}]})},m:b=>{var a=Da[b];delete Da[b];var c=a.ta,d=a.ma,e=a.Ga,g=e.map(h=>h.za).concat(e.map(h=>h.Ca));P([b],g,h=>{var f={};e.forEach((k,m)=>{var l=h[m],p=k.xa,r=k.ya,w=h[m+e.length],t=k.Ba,u=k.Da;f[k.La]={read:C=>l.fromWireType(p(r,C)),write:(C,K)=>{var z=[];t(u,C,w.toWireType(z,K));Ba(z)}}});return[{name:a.name,fromWireType:k=>{var m={},l;for(l in f)m[l]=f[l].read(k);d(k);return m},toWireType:(k,
m)=>{for(var l in f)if(!(l in m))throw new TypeError(`Missing field: "${l}"`);var p=c();for(l in f)f[l].write(p,m[l]);null!==k&&k.push(d,p);return p},ka:8,readValueFromPointer:J,la:d}]})},x:()=>{},H:(b,a,c,d)=>{a=Q(a);O(b,{name:a,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},ka:8,readValueFromPointer:function(e){return this.fromWireType(B[e])},la:null})},j:(b,a,c,d,e,g,h,f,k,m,l,p,r)=>{l=Q(l);g=V(e,g);f&&=V(h,f);m&&=V(k,m);r=V(p,r);var w=Ta(l);Sa(w,function(){hb(`Cannot construct ${l} due to unbound types`,
[d])});P([b,a,c],d?[d]:[],t=>{t=t[0];if(d){var u=t.ea;var C=u.pa}else C=Qa.prototype;t=T(l,function(...Fa){if(Object.getPrototypeOf(this)!==K)throw new R("Use 'new' to construct "+l);if(void 0===z.oa)throw new R(l+" has no accessible constructor");var jb=z.oa[Fa.length];if(void 0===jb)throw new R(`Tried to invoke ctor of ${l} with invalid number of parameters (${Fa.length}) - expected (${Object.keys(z.oa).toString()}) parameters instead!`);return jb.apply(this,Fa)});var K=Object.create(C,{constructor:{value:t}});
t.prototype=K;var z=new Ua(l,t,K,r,u,g,f,m);if(z.ja){var W;(W=z.ja).Ea??(W.Ea=[]);z.ja.Ea.push(z)}u=new $a(l,z,!0,!1,!1);W=new $a(l+"*",z,!1,!1,!1);C=new $a(l+" const*",z,!1,!0,!1);La[b]={pointerType:W,Ia:C};ab(w,t);return[u,W,C]})},h:(b,a,c,d,e,g)=>{var h=ib(a,c);e=V(d,e);P([],[b],f=>{f=f[0];var k=`constructor ${f.name}`;void 0===f.ea.oa&&(f.ea.oa=[]);if(void 0!==f.ea.oa[a-1])throw new R(`Cannot register multiple constructors with identical number of parameters (${a-1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
f.ea.oa[a-1]=()=>{hb(`Cannot construct ${f.name} due to unbound types`,h)};P([],h,m=>{m.splice(1,0,null);f.ea.oa[a-1]=lb(k,m,null,e,g);return[]});return[]})},a:(b,a,c,d,e,g,h,f)=>{var k=ib(c,d);a=Q(a);a=mb(a);g=V(e,g);P([],[b],m=>{function l(){hb(`Cannot call ${p} due to unbound types`,k)}m=m[0];var p=`${m.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);f&&m.ea.Qa.push(a);var r=m.ea.pa,w=r[a];void 0===w||void 0===w.ha&&w.className!==m.name&&w.qa===c-2?(l.qa=c-2,l.className=m.name,r[a]=
l):(Ra(r,a,p),r[a].ha[c-2]=l);P([],k,t=>{t=lb(p,t,m,g,h);void 0===r[a].ha?(t.qa=c-2,r[a]=t):r[a].ha[c-2]=t;return[]});return[]})},E:(b,a,c)=>{b=Q(b);P([],[a],d=>{d=d[0];n[b]=d.fromWireType(c);return[]})},G:b=>O(b,qb),i:(b,a,c,d)=>{function e(){}a=Q(a);e.values={};O(b,{name:a,constructor:e,fromWireType:function(g){return this.constructor.values[g]},toWireType:(g,h)=>h.value,ka:8,readValueFromPointer:rb(a,c,d),la:null});Sa(a,e)},c:(b,a,c)=>{var d=sb(b,"enum");a=Q(a);b=d.constructor;d=Object.create(d.constructor.prototype,
{value:{value:c},constructor:{value:T(`${d.name}_${a}`,function(){})}});b.values[c]=d;b[a]=d},t:(b,a,c)=>{a=Q(a);O(b,{name:a,fromWireType:d=>d,toWireType:(d,e)=>e,ka:8,readValueFromPointer:tb(a,c),la:null})},g:(b,a,c,d,e,g)=>{var h=ib(a,c);b=Q(b);b=mb(b);e=V(d,e);Sa(b,function(){hb(`Cannot call ${b} due to unbound types`,h)},a-1);P([],h,f=>{f=[f[0],null].concat(f.slice(1));ab(b,lb(b,f,null,e,g),a-1);return[]})},f:(b,a,c,d,e)=>{a=Q(a);-1===e&&(e=4294967295);e=f=>f;if(0===d){var g=32-8*c;e=f=>f<<g>>>
g}var h=a.includes("unsigned")?function(f,k){return k>>>0}:function(f,k){return k};O(b,{name:a,fromWireType:e,toWireType:h,ka:8,readValueFromPointer:ub(a,c,0!==d),la:null})},b:(b,a,c)=>{function d(g){return new e(ma.buffer,G[g+4>>2],G[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][a];c=Q(c);O(b,{name:c,fromWireType:d,ka:8,readValueFromPointer:d},{Oa:!0})},s:(b,a)=>{a=Q(a);var c="std::string"===a;O(b,{name:a,fromWireType:function(d){var e=
G[d>>2],g=d+4;if(c)for(var h=g,f=0;f<=e;++f){var k=g+f;if(f==e||0==B[k]){h=h?wb(B,h,k-h):"";if(void 0===m)var m=h;else m+=String.fromCharCode(0),m+=h;h=k+1}}else{m=Array(e);for(f=0;f<e;++f)m[f]=String.fromCharCode(B[g+f]);m=m.join("")}X(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g,h="string"==typeof e;if(!(h||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new R("Cannot pass non-string to std::string");var f;if(c&&
h)for(g=f=0;g<e.length;++g){var k=e.charCodeAt(g);127>=k?f++:2047>=k?f+=2:55296<=k&&57343>=k?(f+=4,++g):f+=3}else f=e.length;g=f;f=Ob(4+g+1);k=f+4;G[f>>2]=g;if(c&&h){if(h=k,k=g+1,g=B,0<k){k=h+k-1;for(var m=0;m<e.length;++m){var l=e.charCodeAt(m);if(55296<=l&&57343>=l){var p=e.charCodeAt(++m);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(h>=k)break;g[h++]=l}else{if(2047>=l){if(h+1>=k)break;g[h++]=192|l>>6}else{if(65535>=l){if(h+2>=k)break;g[h++]=224|l>>12}else{if(h+3>=k)break;g[h++]=240|l>>18;g[h++]=
128|l>>12&63}g[h++]=128|l>>6&63}g[h++]=128|l&63}}g[h]=0}}else if(h)for(h=0;h<g;++h){m=e.charCodeAt(h);if(255<m)throw X(k),new R("String has UTF-16 code units that do not fit in 8 bits");B[k+h]=m}else for(h=0;h<g;++h)B[k+h]=e[h];null!==d&&d.push(X,f);return f},ka:8,readValueFromPointer:J,la(d){X(d)}})},l:(b,a,c)=>{c=Q(c);if(2===a){var d=yb;var e=zb;var g=Ab;var h=f=>E[f>>1]}else 4===a&&(d=Bb,e=Cb,g=Db,h=f=>G[f>>2]);O(b,{name:c,fromWireType:f=>{for(var k=G[f>>2],m,l=f+4,p=0;p<=k;++p){var r=f+4+p*a;
if(p==k||0==h(r))l=d(l,r-l),void 0===m?m=l:(m+=String.fromCharCode(0),m+=l),l=r+a}X(f);return m},toWireType:(f,k)=>{if("string"!=typeof k)throw new R(`Cannot pass non-string to C++ string type ${c}`);var m=g(k),l=Ob(4+m+a);G[l>>2]=m/a;e(k,l+4,m+a);null!==f&&f.push(X,l);return l},ka:8,readValueFromPointer:J,la(f){X(f)}})},q:(b,a,c,d,e,g)=>{Aa[b]={name:Q(a),ta:V(c,d),ma:V(e,g),elements:[]}},D:(b,a,c,d,e,g,h,f,k)=>{Aa[b].elements.push({za:a,xa:V(c,d),ya:e,Ca:g,Ba:V(h,f),Da:k})},r:(b,a,c,d,e,g)=>{Da[b]=
{name:Q(a),ta:V(c,d),ma:V(e,g),Ga:[]}},k:(b,a,c,d,e,g,h,f,k,m)=>{Da[b].Ga.push({La:Q(a),za:c,xa:V(d,e),ya:g,Ca:h,Ba:V(f,k),Da:m})},I:(b,a)=>{a=Q(a);O(b,{Ta:!0,name:a,ka:0,fromWireType:()=>{},toWireType:()=>{}})},o:(b,a,c,d)=>{b=Eb[b];a=pb(a);return b(null,a,c,d)},e:(b,a,c,d,e)=>{b=Eb[b];a=pb(a);c=Gb(c);return b(a,a[c],d,e)},J:ob,v:b=>{if(0===b)return U(Hb());b=Gb(b);return U(Hb()[b])},d:(b,a,c)=>{var d=Jb(b,a),e=d.shift();b--;var g=Array(b);a=`methodCaller<(${d.map(h=>h.name).join(", ")}) => ${e.name}>`;
return Ib(T(a,(h,f,k,m)=>{for(var l=0,p=0;p<b;++p)g[p]=d[p].readValueFromPointer(m+l),l+=d[p].ka;f=1===c?Kb(f,g):f.apply(h,g);h=[];f=e.toWireType(h,f);h.length&&(G[k>>2]=U(h));return f}))},n:b=>{9<b&&(Y[b+1]+=1)},K:()=>U([]),C:b=>U(Gb(b)),B:b=>{var a=pb(b);Ba(a);ob(b)},F:(b,a)=>{b=sb(b,"_emval_take_value");b=b.readValueFromPointer(a);return U(b)},y:b=>{var a=B.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(b,
d)/65536))-A.buffer.byteLength+65535)/65536|0;try{A.grow(d);pa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},z:()=>52,w:function(){return 70},p:(b,a,c,d)=>{for(var e=0,g=0;g<c;g++){var h=G[a>>2],f=G[a+4>>2];a+=8;for(var k=0;k<f;k++){var m=B[h+k],l=Lb[b];0===m||10===m?((1===b?ka:y)(wb(l)),l.length=0):l.push(m)}e+=f}G[d>>2]=e;return 0}},Z=function(){H++;var b={a:Pb};wa??=va("pathkit.wasm")?"pathkit.wasm":q+n.locateFile("pathkit.wasm");za(b,function(a){Z=a.instance.exports;A=Z.L;pa();bb=Z.$;ra.unshift(Z.M);
H--;0==H&&(null!==ta&&(clearInterval(ta),ta=null),I&&(a=I,I=null,a()))}).catch(ba);return{}}(),fb=b=>(fb=Z.N)(b);n.__Z6ToCmdsRK6SkPath=(b,a)=>(n.__Z6ToCmdsRK6SkPath=Z.O)(b,a);n.__Z8FromCmdsmi=(b,a,c)=>(n.__Z8FromCmdsmi=Z.P)(b,a,c);n.__Z7NewPathv=b=>(n.__Z7NewPathv=Z.Q)(b);n.__Z8CopyPathRK6SkPath=(b,a)=>(n.__Z8CopyPathRK6SkPath=Z.R)(b,a);n.__Z6EqualsRK6SkPathS1_=(b,a)=>(n.__Z6EqualsRK6SkPathS1_=Z.S)(b,a);n.__Z11ToSVGStringRK6SkPath=(b,a)=>(n.__Z11ToSVGStringRK6SkPath=Z.T)(b,a);
n.__Z13FromSVGStringNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE=(b,a)=>(n.__Z13FromSVGStringNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE=Z.U)(b,a);n.__Z13ApplySimplifyR6SkPath=b=>(n.__Z13ApplySimplifyR6SkPath=Z.V)(b);n.__Z11ApplyPathOpR6SkPathRKS_8SkPathOp=(b,a,c)=>(n.__Z11ApplyPathOpR6SkPathRKS_8SkPathOp=Z.W)(b,a,c);n.__Z10MakeFromOpRK6SkPathS1_8SkPathOp=(b,a,c,d)=>(n.__Z10MakeFromOpRK6SkPathS1_8SkPathOp=Z.X)(b,a,c,d);
n.__Z14ResolveBuilderR11SkOpBuilder=(b,a)=>(n.__Z14ResolveBuilderR11SkOpBuilder=Z.Y)(b,a);n.__Z8ToCanvasRK6SkPathN10emscripten3valE=(b,a)=>(n.__Z8ToCanvasRK6SkPathN10emscripten3valE=Z.Z)(b,a);n.__Z8ToPath2DRK6SkPath=(b,a)=>(n.__Z8ToPath2DRK6SkPath=Z._)(b,a);var X=b=>(X=Z.aa)(b),Ob=b=>(Ob=Z.ba)(b);n.dynCall_jiji=(b,a,c,d,e)=>(n.dynCall_jiji=Z.ca)(b,a,c,d,e);var Qb;I=function Rb(){Qb||Sb();Qb||(I=Rb)};
function Sb(){if(!(0<H)){for(;0<qa.length;)qa.shift()(n);if(!(0<H||Qb||(Qb=!0,n.calledRun=!0,la))){for(;0<ra.length;)ra.shift()(n);for(aa(n);0<sa.length;)sa.shift()(n)}}}Sb();moduleRtn=ca;


  return moduleRtn;
}
);
})();
// if (typeof exports === 'object' && typeof module === 'object')
//   module.exports = PathKitInit;
// else if (typeof define === 'function' && define['amd'])
//   define([], () => PathKitInit);
export default async (opts)=>{
  let PathKit=await PathKitInit(opts)
  PathKit.onRuntimeInitialized()
  return PathKit
}